apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-pipe-config
  namespace: fluentd-pipe
data:
  fluent.conf: |
    <source>
      @type http
      port 24226
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
    </source>
    <match **>
      @type copy
      <store>
        @type kafka2
        brokers 10.210.149.25:9092,10.210.149.26:9092,10.210.149.27:9092
        default_topic alertmanager
        <format>
          @type json
        </format>
      </store>
      <store>
        @type file
        path /tmp/alertmanager
        time_slice_format %Y%m%d
      </store>
    </match> 
