kind: Service
apiVersion: v1
metadata:
  name: fluentd-pipe-svc
  namespace: fluentd-pipe
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: fluentd-pipe
  ports:
  - name: alert-port
    port: 32010
    nodePort: 32010
    targetPort: 32010
