apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-messages-deploy
  namespace: fbit-hub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: syslog-messages
  template:
    metadata:
      labels:
        app: syslog-messages
    spec:
      containers:
        - name: syslog-messages
          image: docker.io/fluent/fluent-bit
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics-port
            containerPort: 2020
          - name: log-port
            containerPort: 32101
