kind: Service
apiVersion: v1
metadata:
  name: syslog-audit-svc
  namespace: fbit-hub
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: syslog-audit
  ports:
  - name: audit-port
    port: 32102
    nodePort: 32102
    targetPort: 32102
