apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-message-deploy
  namespace: fbit-hub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: syslog-messages
  template:
    metadata:
      labels:
        app: syslog-messages
    spec:
      containers:
        - name: syslog-message
          image: docker.io/fluent/fluentd
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics-port
            containerPort: 24231
          - name: messages-port
            containerPort: 32101
          command: ['/bin/sh', '-c']
          args:
            - /usr/bin/gem install fluent-plugin-alertmanager fluent-plugin-prometheus fluent-plugin-kafka fluent-plugin-route;
              /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins;
          volumeMounts:
          - name: messages-config
            mountPath: "/fluentd/etc/"
      volumes:
      - name: syslog-messages-config
        configMap:
          name: syslog-messages-config
