apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8slog-core-deploy
  namespace: fbit-hub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8slog-core
  template:
    metadata:
      labels:
        app: k8slog-core
    spec:
      containers:
        - name: k8slog-core
          image: docker.io/fluent/fluentd
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics-port
            containerPort: 24231
          - name: core-port
            containerPort: 32111
          command: ['/bin/sh', '-c']
          args:
            - /usr/bin/gem install fluent-plugin-alertmanager fluent-plugin-prometheus fluent-plugin-kafka fluent-plugin-route;
              /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins;
          volumeMounts:
          - name: k8slog-core-config
            mountPath: "/fluentd/etc/"
      volumes:
      - name: k8slog-core-config
        configMap:
          name: k8slog-core-config
