kind: Service
apiVersion: v1
metadata:
  name: k8slog-core-svc
  namespace: fbit-hub
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: k8slog-core
  ports:
  - name: core-port
    port: 32111
    nodePort: 32111
    targetPort: 32111
