kind: Service
apiVersion: v1
metadata:
  name: nginx-error-svc
  namespace: fbit-hub
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: nginx-error
  ports:
  - name: error-port
    port: 32122
    nodePort: 32122
    targetPort: 32122
