---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    name: prometheus-deployment
  name: prometheus
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: prom/prometheus:latest
        name: prometheus
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=24h"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
        - mountPath: "/etc/prometheus/targets"
          name: config-volume-targets
        - mountPath: "/etc/prometheus/targets/node_exporter"
          name: config-targets-nodeexporter
        - mountPath: "/etc/prometheus/rules"
          name: config-volume-rules
        - mountPath: "/etc/prometheus/targets/ceph"
          name: config-targets-ceph
        - mountPath: "/etc/prometheus/targets/federate"
          name: config-targets-federate
        - mountPath: "/etc/prometheus/targets/etcd"
          name: config-targets-etcd
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      serviceAccountName: prometheus
      imagePullSecrets: 
        - name: regsecret
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: config-volume-rules
        configMap:
          name: config-rules-default
      - name: config-volume-targets
        emptyDir: {}
      - name: config-targets-nodeexporter
        configMap:
          name: prometheus-config-nodeexporter
      - name: config-targets-ceph
        emptyDir: {}
      - name: config-targets-federate
        emptyDir: {}
      - name: config-targets-etcd
        emptyDir: {}
