apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-collector-deploy
  namespace: fluentd-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-collector
  template:
    metadata:
      labels:
        app: fluentd-collector
    spec:
      containers:
        - name: fluentd-collector
          image: docker.io/fluent/fluentd
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics-port
            containerPort: 24231
          command: ['/bin/sh', '-c']
          args:
            - /usr/bin/gem install fluent-plugin-elasticsearch fluent-plugin-alertmanager fluent-plugin-prometheus fluent-plugin-kafka;
              /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins;
          volumeMounts:
          - name: fluentd-config
            mountPath: "/fluentd/etc/"
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-collector-config
