apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-access-deploy
  namespace: fbit-hub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-access
  template:
    metadata:
      labels:
        app: nginx-access
    spec:
      containers:
        - name: nginx-access
          image: docker.io/fluent/fluentd
          imagePullPolicy: IfNotPresent
          ports:
          - name: metrics-port
            containerPort: 24231
          - name: access-port
            containerPort: 32121
          command: ['/bin/sh', '-c']
          args:
            - /usr/bin/gem install fluent-plugin-alertmanager fluent-plugin-prometheus fluent-plugin-kafka fluent-plugin-route;
              /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins;
          volumeMounts:
          - name: nginx-access-config 
            mountPath: "/fluentd/etc/"
      volumes:
      - name: nginx-access-config
        configMap:
          name: nginx-access-config
