apiVersion: v1
kind: ConfigMap
metadata:
  name: syslog-messages-config
  namespace: fbit-hub
data:
  fluent.conf: |
    # promethues metrics
    <source>
      @type prometheus
    </source>
  
    <source>
      @type prometheus_output_monitor
      <labels>
        host ${hostname}
      </labels>
    </source>
  
    <source>
      @type prometheus_tail_monitor
      <labels>
        host ${hostname}
      </labels>
    </source>

    # message input
    <source>
      @type forward
      @label @MESSAGES
      port 32101
      <parse>
        @type syslog
      </parse>
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
    </source>

    <label @MESSAGES>
      <filter **>
        @type record_transformer
        <record>
          log_ident syslog.messages
        </record>
      </filter>
      <match **>
        @type route
        add_tag_prefix syslog.messages
        <route **>
          copy
          @label @MESSAGES_ALERT
        </route>
        <route **>
          copy
          @label @MESSAGES_KAFKA
        </route>
      </match>
    </label>

    <label @MESSAGES_ALERT>
      <filter **>
        @type grep
        <regexp>
          key ident
          pattern su
        </regexp>
      </filter>
      <filter **>
        @type record_transformer
        <record>
          tag ${tag}
          labels {"alertname": "${tag}-${time}","serverity": "critical","host": "${record[\"host\"]}","ident": "su"}
          annotations {"summary": "${tag}","description": "${record[\"message\"]}"}
        </record>
      </filter>
      <match **>
        @type alertmanager
        endpoint_url http://alertmanager.ekaexhz.seli.gic.ericsson.se:9093/api/v1/alerts
      </match>
    </label>

    <label @MESSAGES_KAFKA>
      <match **>
        @type copy
        <store>
          @type kafka2
          brokers 10.210.149.25:9092,10.210.149.26:9092,10.210.149.27:9092
          default_topic syslog.messages
          <format>
            @type json
          </format>
        </store>
        <store>
          @type file
          path /tmp/messages
          time_slice_format %Y%m%d
          <format>
            @type json
          </format>
        </store>
      </match>
    </label>
