kind: Service
apiVersion: v1
metadata:
  name: nginx-access-svc
  namespace: fbit-hub
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: nginx-access
  ports:
  - name: access-port
    port: 32121
    nodePort: 32121
    targetPort: 32121
