kind: Service
apiVersion: v1
metadata:
  name: k8slog-app-svc
  namespace: fbit-hub
spec:
  type: NodePort
  #clusterIP: None
  selector:
    app: k8slog-app
  ports:
  - name: messages-port
    port: 32112
    nodePort: 32112
    targetPort: 32112
